### ISSUE TITLE
No output on Ubuntu WSL

### ISSUE THREAD

**Issue by felipecustodio** [ashutoshbsathe/yacv#1]
Ubuntu-20.04 on [WSL](https://docs.microsoft.com/en-us/windows/wsl/), installation using `pip3 install -e .` was successful. 
Running the example `python3  -m yacv ll1-parsing-example.yml`, resulted in no output from the logger and no `yacv_ll1-simple/` was created.

Could be a problem with dependencies, or some error thrown by external tools like graphviz.
Is there a way to run yacv in a verbose mode, for debugging?

**Comment by ashutoshbsathe** [comment]
I'm using python logging so you can set logging level to debug and check the output (this may log a LOT of stuff though)

Let me know how it goes. I'm not quite sure how well manim/pygraphviz will work in WSL. What version of Manim are you using ? ManimGL or ManimCE ?  

Can you also tell me what directory you ran the command from ? The configs from yacv/examples directory are to be run from yacv/examples itself. Whereas yacv/example_config.yml must be run from yacv/

**Comment by ashutoshbsathe** [comment]
77a948c should fix the issue. I missed an entry point for command line "-m" option

`git pull` and see if it works for now

**Comment by felipecustodio** [comment]
@ashutoshbsathe that fixed it! =)
working perfectly now, thanks for the replies!
