### ISSUE TITLE
Remove system specific path

### ISSUE THREAD

**Issue by yashshah1** [ashutoshbsathe/yacv#2]
Not sure what functionality this adds, but ideally shouldn't exist in a code base that is distributed. Replace it with something more generic (since an importable library shouldn't need to mess with env vars)? If needed, possibly add a note in the docs for additional setup instructions?

https://github.com/ashutoshbsathe/yacv/blob/77a948c66f481f1d13b1f84cc9a88ddcdbe7d2d2/yacv/vis.py#L3

**Comment by ashutoshbsathe** [comment]
Thanks a lot for noticing. That line should not be there. It was required initially when I would pass the `.py` file to manim. Now the library itself can initialize manim properly

a3256e8 fixes it
Thanks for noticing :)
